app = "simpleagent-backend"
primary_region = "sin"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "30000"

[[services]]
  internal_port = 30000
  protocol = "http"

  [[services.ports]]
    port = 30000

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    path = "/api/health"